/**
 * 诗语雅集 · 中国传统色谱
 * 参照《天工开物》《说文解字》《中国色名综览》《敦煌壁画色谱》
 * 每种颜色配一句经典古诗
 */

export interface ChineseColor {
  name: string
  hex: string
  rgb: string
  category: Category
  poem?: string   // 硬编码兜底（已废弃，优先动态）
  source?: string // 硬编码兜底（已废弃，优先动态）
  alias?: string
  note?: string   // 可选备注（如矿物名、典故出处）
}

export type Category =
  | 'red'      // 赤
  | 'yellow'   // 黄
  | 'green'    // 青
  | 'blue'     // 蓝
  | 'purple'   // 紫
  | 'white'    // 白
  | 'black'    // 玄
  | 'mineral'  // 矿物·金石
  | 'imagery'  // 诗词·意象
  | 'solar'    // 节气·流光

export const CATEGORY_LABELS: Record<Category, string> = {
  red:     '赤',
  yellow:  '黄',
  green:   '青',
  blue:    '蓝',
  purple:  '紫',
  white:   '白',
  black:   '玄',
  mineral: '金石',
  imagery: '意象',
  solar:   '节气',
}

export const CHINESE_COLORS: ChineseColor[] = [

  // ══════════════════════════════════════════════════════
  // 【壹·赤色系】天地间第一正色
  // 《说文》："赤，南方之色，从大、从火。"
  // ══════════════════════════════════════════════════════

  {
    name: '绛紫',
    hex: '#7B2D26',
    rgb: '123,45,38',
    category: 'red',
    poem: '千里莺啼绿映红，水村山郭酒旗风',
    source: '《江南春》· 杜牧',
    note: '绛为深红之正色，古为军服色',
  },
  {
    name: '胭脂',
    hex: '#9B3A2A',
    rgb: '155,58,42',
    category: 'red',
    poem: '人面桃花相映红，人面不知何处去',
    source: '《题都城南庄》· 崔护',
    note: '古以红蓝花制，妇人妆面用之',
  },
  {
    name: '朱砂',
    hex: '#C24B40',
    rgb: '194,75,64',
    category: 'red',
    poem: '朱门酒肉臭，路有冻死骨',
    source: '《自京赴奉先县咏怀五百字》· 杜甫',
    note: '硫化汞矿物，道家炼丹之物',
  },
  {
    name: '曙红',
    hex: '#E05B4A',
    rgb: '224,91,74',
    category: 'red',
    poem: '落红不是无情物，化作春泥更护花',
    source: '《己亥杂诗》· 龚自珍',
    note: '黎明天际第一缕红光',
  },
  {
    name: '檀色',
    hex: '#A0522D',
    rgb: '160,82,45',
    category: 'red',
    poem: '水纹珍簟思悠悠，千里佳期一夕休',
    source: '《瑶瑟怨》· 李商隐',
    note: '檀木心材之色，沉静古雅',
  },
  {
    name: '茜色',
    hex: '#C94055',
    rgb: '201,64,85',
    category: 'red',
    poem: '茜裙偷典卖花钿，恼人无柰春风何',
    source: '《宫词》· 无名氏',
    note: '茜草根可染绛红，古诗"茜"多指女红',
  },
  {
    name: '彤色',
    hex: '#D94F4F',
    rgb: '217,79,79',
    category: 'red',
    poem: '日出江花红胜火，春来江水绿如蓝',
    source: '《忆江南》· 白居易',
    note: '彤本义为赤色丹漆，《诗经》"彤管"',
  },
  {
    name: '绯红',
    hex: '#E84A5F',
    rgb: '232,74,95',
    category: 'red',
    poem: '桃花一簇开无主，可爱深红爱浅红',
    source: '《江畔独步寻花》· 杜甫',
    note: '绯为古时官服色，唐制四品服绯',
  },
  {
    name: '赭红',
    hex: '#B5483A',
    rgb: '181,72,58',
    category: 'red',
    poem: '半卷红旗临易水，霜重鼓寒声不起',
    source: '《雁门太守行》· 李贺',
    note: '赭石烧制，敦煌壁画常用色',
  },
  {
    name: '殷红',
    hex: '#8B2942',
    rgb: '139,41,66',
    category: 'red',
    poem: '林花谢了春红，太匆匆',
    source: '《乌夜啼》· 李煜',
    note: '殷为深赤色，《说文》"微黑色也"',
  },
  {
    name: '丹红',
    hex: '#C23B22',
    rgb: '194,59,34',
    category: 'red',
    poem: '丹霞出海暾，晓日半天红',
    source: '《晓望》· 陆游',
    note: '丹砂之红，道家炼丹求长生',
  },
  {
    name: '赤金',
    hex: '#CC7A29',
    rgb: '204,122,41',
    category: 'red',
    poem: '金樽清酒斗十千，玉盘珍羞直万钱',
    source: '《行路难》· 李白',
    note: '赤铜之色，古称"绛金"',
  },
  {
    name: '石榴红',
    hex: '#CE3A4E',
    rgb: '206,58,78',
    category: 'red',
    poem: '可怜此地无车马，颠倒苍苔落绛英',
    source: '《惜春》· 杜牧',
    note: '石榴花之红，唐代女子喜以此点唇',
  },
  {
    name: '骍黄',
    hex: '#C87040',
    rgb: '200,112,64',
    category: 'red',
    poem: '骍骍角弓，翩其反矣',
    source: '《诗经·角弓》',
    note: '骍为赤黄色，《诗经》名物',
  },
  {
    name: '退红',
    hex: '#E8A0A0',
    rgb: '232,160,160',
    category: 'red',
    poem: '桃花轻薄逐流水，落红万点愁如海',
    source: '《暮春》· 无名氏',
    note: '宋代女子习用退红敷面，见《东京梦华录》',
  },
  {
    name: '撷下春',
    hex: '#F0A0B0',
    rgb: '240,160,176',
    category: 'red',
    poem: '绿杨烟外晓寒轻，红杏枝头春意闹',
    source: '《玉楼春》· 宋祁',
    note: '宋人称春日女子颊上薄红为"撷下春"',
  },
  {
    name: '杏红',
    hex: '#E87850',
    rgb: '232,120,80',
    category: 'red',
    poem: '绿杨芳草长亭路，年少抛人容易去',
    source: '《蝶恋花》· 晏殊',
    note: '杏子熟时外皮之色',
  },
  {
    name: '缙红',
    hex: '#B8302B',
    rgb: '184,48,43',
    category: 'red',
    poem: '缙云山色望中奇，晴日花光照石眉',
    source: '《缙云山》· 无名氏',
    note: '缙为赤色帛，古以赤色丝带记事',
  },

  // ══════════════════════════════════════════════════════
  // 【贰·黄色系】土之正色，王权之色
  // 《说文》："黄，地之色也。"
  // ══════════════════════════════════════════════════════

  {
    name: '明黄',
    hex: '#F5D060',
    rgb: '245,208,96',
    category: 'yellow',
    poem: '冲天香阵透长安，满城尽带黄金甲',
    source: '《不第后赋菊》· 黄巢',
    note: '清代帝王专用色，前代明黄为最尊',
  },
  {
    name: '鹅黄',
    hex: '#F0D58C',
    rgb: '240,213,140',
    category: 'yellow',
    poem: '鹅黄染就春衫袖，蜂蝶纷纷惯往来',
    source: '《春词》· 无名氏',
    note: '春日柳芽初萌之色，如小鹅绒毛',
  },
  {
    name: '藤黄',
    hex: '#E8B84B',
    rgb: '232,184,75',
    category: 'yellow',
    poem: '黄金白羽黄鹄飞，少年意气何时归',
    source: '《少年行》· 李白',
    note: '国画矿物颜料，藤蔓汁液制，稳定性佳',
  },
  {
    name: '柘黄',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'yellow',
    poem: '柘叶青时处处同，采叶归来煮碧筒',
    source: '《柘叶》· 无名氏',
    note: '柘木心材染黄，唐代龙袍之色',
  },
  {
    name: '缃色',
    hex: '#E8C87A',
    rgb: '232,200,122',
    category: 'yellow',
    poem: '缃绮为下裙，紫绮为上襦',
    source: '《陌上桑》· 汉乐府',
    note: '浅黄如绢帛，古时女子服饰常用',
  },
  {
    name: '金黄',
    hex: '#DAA520',
    rgb: '218,165,32',
    category: 'yellow',
    poem: '金樽清酒斗十千，玉盘珍羞直万钱',
    source: '《行路难》· 李白',
    note: '黄金本色，贵族显赫之象征',
  },
  {
    name: '杏黄',
    hex: '#E8A838',
    rgb: '232,168,56',
    category: 'yellow',
    poem: '杏园花落遍春城，愁杀行人空断肠',
    source: '《杏园》· 姚合',
    note: '杏子将熟时果皮之色',
  },
  {
    name: '菊黄',
    hex: '#D9A435',
    rgb: '217,164,53',
    category: 'yellow',
    poem: '待到秋来九月八，我花开后百花杀',
    source: '《不第后赋菊》· 黄巢',
    note: '寒菊傲霜之色，陶渊明独爱此色',
  },
  {
    name: '米黄',
    hex: '#F5E6C8',
    rgb: '245,230,200',
    category: 'yellow',
    poem: '黄云白草春风起，驱马归来日未斜',
    source: '《边词》· 张敬忠',
    note: '如小米脱壳后的本色，温和不刺眼',
  },
  {
    name: '土黄',
    hex: '#C8A86B',
    rgb: '200,168,107',
    category: 'yellow',
    poem: '大漠沙如雪，燕山月似钩',
    source: '《马诗》· 李贺',
    note: '大地本色，厚重沉稳',
  },
  {
    name: '姜黄',
    hex: '#C9902A',
    rgb: '201,144,42',
    category: 'yellow',
    poem: '中庭地白树栖鸦，冷露无声湿桂花',
    source: '《十五夜望月》· 王建',
    note: '姜黄块根染色，敦煌壁画常用',
  },
  {
    name: '秋香',
    hex: '#C8A84B',
    rgb: '200,168,75',
    category: 'yellow',
    poem: '秋风吹不尽，总是玉关情',
    source: '《子夜秋歌》· 李白',
    note: '秋日草木黄熟之气，略带绿意',
  },
  {
    name: '沙黄',
    hex: '#D4B86A',
    rgb: '212,184,106',
    category: 'yellow',
    poem: '大漠孤烟直，长河落日圆',
    source: '《使至塞上》· 王维',
    note: '戈壁沙漠之色，空旷苍凉',
  },
  {
    name: '雄黄',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'yellow',
    poem: '黄金白羽黄鹄飞，少年意气何时归',
    source: '《少年行》· 李白',
    note: '硫化砷矿物，端午涂额辟邪',
  },
  {
    name: '松花黄',
    hex: '#E8D870',
    rgb: '232,216,112',
    category: 'yellow',
    poem: '松花酿酒，春水煎茶',
    source: '《人月圆》· 张可久',
    note: '松花淡黄之色，文人雅趣',
  },
  {
    name: '秋葵黄',
    hex: '#E0B050',
    rgb: '224,176,80',
    category: 'yellow',
    poem: '葵藿倾太阳，物性固莫夺',
    source: '《自京洛 Advantage 归》· 杜甫',
    note: '黄蜀葵花之色，暮开朝敛',
  },

  // ══════════════════════════════════════════════════════
  // 【叁·青绿色系】东方之正色，木之德
  // 《说文》："青，东方之色也。"
  // ══════════════════════════════════════════════════════

  {
    name: '翠色',
    hex: '#228B22',
    rgb: '34,139,34',
    category: 'green',
    poem: '绿蚁新醅酒，红泥小火炉',
    source: '《问刘十九》· 白居易',
    note: '翡翠鸟羽之色，鲜活明快',
  },
  {
    name: '碧色',
    hex: '#3CB371',
    rgb: '60,179,113',
    category: 'green',
    poem: '春来江水绿如蓝，能不忆江南',
    source: '《忆江南》· 白居易',
    note: '蓝草（蓼蓝）可制靛青，故云"绿如蓝"',
  },
  {
    name: '松绿',
    hex: '#2D6A4F',
    rgb: '45,106,79',
    category: 'green',
    poem: '松风吹解带，山月照弹琴',
    source: '《酬张少府》· 王维',
    note: '苍松古干之色，沉稳内敛',
  },
  {
    name: '苍翠',
    hex: '#3D7A5A',
    rgb: '61,122,90',
    category: 'green',
    poem: '绿树村边合，青山郭外斜',
    source: '《过故人庄》· 孟浩然',
    note: '山间林木深秀之色',
  },
  {
    name: '葱绿',
    hex: '#7CB342',
    rgb: '124,179,66',
    category: 'green',
    poem: '桃红柳绿又一春，莺啼燕语报新年',
    source: '《元日》· 王安石',
    note: '葱叶嫩绿之色，盎然生机',
  },
  {
    name: '豆绿',
    hex: '#6B9B4F',
    rgb: '107,155,79',
    category: 'green',
    poem: '绿肥红瘦，知否知否，应是绿肥红瘦',
    source: '《如梦令》· 李清照',
    note: '青豆剥开之色，清新柔和',
  },
  {
    name: '竹青',
    hex: '#4D8B68',
    rgb: '77,139,104',
    category: 'green',
    poem: '竹喧归浣女，莲动下渔舟',
    source: '《山居秋暝》· 王维',
    note: '竹竿表皮之色，青皮竹',
  },
  {
    name: '荷绿',
    hex: '#5DAE8B',
    rgb: '93,174,139',
    category: 'green',
    poem: '接天莲叶无穷碧，映日荷花别样红',
    source: '《晓出净慈寺送林子方》· 杨万里',
    note: '莲叶铺展之色，江南夏景',
  },
  {
    name: '青苔绿',
    hex: '#4A7C59',
    rgb: '74,124,89',
    category: 'green',
    poem: '返景入深林，复照青苔上',
    source: '《鹿柴》· 王维',
    note: '幽林苔藓之色，古意盎然',
  },
  {
    name: '鸦青',
    hex: '#3D6B4A',
    rgb: '61,107,74',
    category: 'green',
    poem: '两个黄鹂鸣翠柳，一行白鹭上青天',
    source: '《绝句》· 杜甫',
    note: '鸦羽深青之色，带墨绿底调',
  },
  {
    name: '黛绿',
    hex: '#556B2F',
    rgb: '85,107,47',
    category: 'green',
    poem: '青山隐隐水迢迢，秋尽江南草未凋',
    source: '《寄扬州韩绑判官》· 杜牧',
    note: '黛为画眉墨，深青带黄褐',
  },
  {
    name: '石绿',
    hex: '#4A8C5E',
    rgb: '74,140,94',
    category: 'green',
    poem: '山回路转不见君，雪山空留马行处',
    source: '《白雪歌送武判官归京》· 岑参',
    note: '孔雀石磨制，国画重彩常用',
  },
  {
    name: '柳绿',
    hex: '#8DB255',
    rgb: '141,178,85',
    category: 'green',
    poem: '杨柳依依绿初齐，此去经年未有期',
    source: '《杨柳》· 无名氏',
    note: '柳叶新芽之色，春风第一抹绿',
  },
  {
    name: '苔绿',
    hex: '#5A8A60',
    rgb: '90,138,96',
    category: 'green',
    poem: '应怜屐齿印苍苔，小扣柴扉久不开',
    source: '《游园不值》· 叶绍翁',
    note: '石阶苔藓之色，幽静古朴',
  },
  {
    name: '松花绿',
    hex: '#8DB255',
    rgb: '141,178,85',
    category: 'green',
    poem: '松花酿酒，春水煎茶',
    source: '《人月圆》· 张可久',
    note: '松花初放之绿',
  },
  {
    name: '草绿',
    hex: '#7CB342',
    rgb: '124,179,66',
    category: 'green',
    poem: '离离原上草，一岁一枯荣',
    source: '《赋得古原草送别》· 白居易',
    note: '草原风吹之色，生生不息',
  },
  {
    name: '油绿',
    hex: '#5A9A60',
    rgb: '90,154,96',
    category: 'green',
    poem: '春风又绿江南岸，明月何时照我还',
    source: '《泊船瓜洲》· 王安石',
    note: '夏木繁荫之色，油润饱满',
  },

  // ══════════════════════════════════════════════════════
  // 【肆·蓝色系】天之色，深邃幽远
  // 《说文》："蓝，染青之草也。"
  // ══════════════════════════════════════════════════════

  {
    name: '靛蓝',
    hex: '#243B6B',
    rgb: '36,59,107',
    category: 'blue',
    poem: '日出江花红胜火，春来江水绿如蓝',
    source: '《忆江南》· 白居易',
    note: '蓼蓝草制靛，我国最早合成颜料之一',
  },
  {
    name: '藏青',
    hex: '#1E3A5F',
    rgb: '30,58,95',
    category: 'blue',
    poem: '青海长云暗雪山，孤城遥望玉门关',
    source: '《从军行》· 王昌龄',
    note: '藏地牦牛毛色，青黑深沉',
  },
  {
    name: '群青',
    hex: '#3A5F8A',
    rgb: '58,95,138',
    category: 'blue',
    poem: '蓝水远从千涧落，玉山高并两峰寒',
    source: '《九日蓝田崔氏庄》· 杜甫',
    note: '青金石研磨，宋画重要蓝色',
  },
  {
    name: '天蓝',
    hex: '#6B8EAD',
    rgb: '107,142,173',
    category: 'blue',
    poem: '天阶夜色凉如水，卧看牵牛织女星',
    source: '《秋夕》· 杜牧',
    note: '晴空澄澈之色，令人心旷神怡',
  },
  {
    name: '蔚蓝',
    hex: '#4A7FBB',
    rgb: '74,127,187',
    category: 'blue',
    poem: '晴空一鹤排云上，便引诗情到碧霄',
    source: '《秋词》· 刘禹锡',
    note: '秋日长空之色，高远澄明',
  },
  {
    name: '普蓝',
    hex: '#1C3879',
    rgb: '28,56,121',
    category: 'blue',
    poem: '蓝田日暖玉生烟，此情可待成追忆',
    source: '《锦瑟》· 李商隐',
    note: '普鲁士蓝引进后的称呼，深沉凝重',
  },
  {
    name: '石青',
    hex: '#3A6B9B',
    rgb: '58,107,155',
    category: 'blue',
    poem: '青山隐隐水迢迢，秋尽江南草未凋',
    source: '《寄扬州韩绑判官》· 杜牧',
    note: '蓝铜矿研磨，敦煌壁画主角色',
  },
  {
    name: '花青',
    hex: '#2E5A88',
    rgb: '46,90,136',
    category: 'blue',
    poem: '青，取之于蓝，而青于蓝',
    source: '《劝学》· 荀子',
    note: '蓝靛提取最浓部分，国画苔点专用',
  },
  {
    name: '绀青',
    hex: '#2B4A8B',
    rgb: '43,74,139',
    category: 'blue',
    poem: '客来无一语，艇子折西湖，绿水涨还绿',
    source: '《湖上》· 姜夔',
    note: '绀为青赤色，略带紫韵',
  },
  {
    name: '品蓝',
    hex: '#2B4E8C',
    rgb: '43,78,140',
    category: 'blue',
    poem: '蓝田有佳气，千载产璚枝',
    source: '《蓝田山石室》· 苏轼',
    note: '蓝田美玉之色，清雅脱俗',
  },
  {
    name: '毛蓝',
    hex: '#3D5F8C',
    rgb: '61,95,140',
    category: 'blue',
    poem: '蓝蓝的天上白云飘，白云下面马儿跑',
    source: '《草原情歌》· 歌词',
    note: '棉布染蓝之色，民间土布常用',
  },
  {
    name: '潮蓝',
    hex: '#4A6FA5',
    rgb: '74,111,165',
    category: 'blue',
    poem: '春江潮水连海平，海上明月共潮生',
    source: '《春江花月夜》· 张若虚',
    note: '潮水映天之色',
  },

  // ══════════════════════════════════════════════════════
  // 【伍·紫色系】间色之美，贵而不骄
  // 《说文》："紫，帛黑赤色也。"
  // ══════════════════════════════════════════════════════

  {
    name: '紫檀',
    hex: '#5B3256',
    rgb: '91,50,86',
    category: 'purple',
    poem: '紫藤挂云木，花蔓宜阳春',
    source: '《紫藤树》· 李白',
    note: '紫檀木之色，古雅深沉',
  },
  {
    name: '藕色',
    hex: '#8E6D8E',
    rgb: '142,109,142',
    category: 'purple',
    poem: '秋阴不散霜飞晚，留得残荷听雨声',
    source: '《宿骆氏亭寄怀崔雍崔衮》· 李商隐',
    note: '莲藕切面之色，淡紫带灰',
  },
  {
    name: '青莲',
    hex: '#6B4C8C',
    rgb: '107,76,140',
    category: 'purple',
    poem: '青莲居士谪仙人，酒肆藏名三十春',
    source: '《答湖州迦叶司马问白是何人》· 李白',
    note: '青莲（莲花）之色，李白自号青莲居士',
  },
  {
    name: '酱紫',
    hex: '#5C3A6B',
    rgb: '92,58,107',
    category: 'purple',
    poem: '紫袖红弦明月中，自弹自感闇低容',
    source: '《夜筝》· 白居易',
    note: '紫酱色，古时女子服饰常用',
  },
  {
    name: '墨紫',
    hex: '#4A2C5A',
    rgb: '74,44,90',
    category: 'purple',
    poem: '紫陌红尘拂面来，无人不道看花回',
    source: '《玄都观桃花》· 刘禹锡',
    note: '紫中带墨，浓重内敛',
  },
  {
    name: '雪青',
    hex: '#9B8AA6',
    rgb: '155,138,166',
    category: 'purple',
    poem: '紫玉千年化鹤归，青山万古埋云冷',
    source: '《过山宫》· 李德裕',
    note: '雪后初晴天空之紫，冷艳高洁',
  },
  {
    name: '紫藤',
    hex: '#7B5EA7',
    rgb: '123,94,167',
    category: 'purple',
    poem: '紫藤挂云木，花蔓宜阳春',
    source: '《紫藤树》· 李白',
    note: '紫藤花穗之色，暮春浪漫',
  },
  {
    name: '黛紫',
    hex: '#4A3A5C',
    rgb: '74,58,92',
    category: 'purple',
    poem: '紫禁通鳧羽，青山绕障泥',
    source: '《早朝日寄所知》· 无名氏',
    note: '黛石之紫，古代女子画眉用黛',
  },
  {
    name: '玫瑰紫',
    hex: '#8B4778',
    rgb: '139,71,120',
    category: 'purple',
    poem: '紫袖红弦明月中，自弹自感闇低容',
    source: '《夜筝》· 白居易',
    note: '玫瑰盛开之紫，娇而不艳',
  },
  {
    name: '茄紫',
    hex: '#5B3D7A',
    rgb: '91,61,122',
    category: 'purple',
    poem: '红绡断肠浑闲事，紫玉无家最可怜',
    source: '《宫词》· 无名氏',
    note: '茄子外皮之色，深沉饱满',
  },
  {
    name: '藕荷',
    hex: '#9B7090',
    rgb: '155,112,144',
    category: 'purple',
    poem: '绿荷舒卷凉风晓，红棹萦回烟渚清',
    source: '《莲》· 无名氏',
    note: '莲荷茎节之色，比藕色更浅',
  },
  {
    name: '东方亮',
    hex: '#8B5A8B',
    rgb: '139,90,139',
    category: 'purple',
    poem: '日出东方，唯我不败',
    source: '《侠客行》· 歌词化用',
    note: '黎明天际微光之紫',
  },
  {
    name: '螺青',
    hex: '#5A5A8A',
    rgb: '90,90,138',
    category: 'purple',
    poem: '青箬笠，绿蓑衣，斜风细雨不须归',
    source: '《渔歌子》· 张志和',
    note: '螺壳内壁青紫之色',
  },
  {
    name: '牢雅紫',
    hex: '#7A3A7A',
    rgb: '122,58,122',
    category: 'purple',
    poem: '紫禁城边春草生，禁城春草不曾歇',
    source: '《宫词》· 无名氏',
    note: '古宫墙紫，沉稳庄重',
  },

  // ══════════════════════════════════════════════════════
  // 【陆·素白色系】素以为绚，水墨至美
  // 《说文》："白，西方之色也。"
  // ══════════════════════════════════════════════════════

  {
    name: '素白',
    hex: '#F5F5F0',
    rgb: '245,245,240',
    category: 'white',
    poem: '白毛浮绿水，红掌拨清波',
    source: '《咏鹅》· 骆宾王',
    note: '素为白色生丝，朴素纯净',
  },
  {
    name: '月白',
    hex: '#E8EEF5',
    rgb: '232,238,245',
    category: 'white',
    poem: '床前明月光，疑是地上霜',
    source: '《静夜思》· 李白',
    note: '月光照地之色，清冷澄澈',
  },
  {
    name: '霜白',
    hex: '#EEF0F5',
    rgb: '238,240,245',
    category: 'white',
    poem: '霜月照积雪，朔风劲且哀',
    source: '《岁暮》· 谢灵运',
    note: '霜降之色，萧瑟凛冽',
  },
  {
    name: '象牙白',
    hex: '#F0EBE0',
    rgb: '240,235,224',
    category: 'white',
    poem: '象牙雕栏十二曲，沉香火底琵琶语',
    source: '《琵琶行》· 白居易',
    note: '象牙本色，温润柔和',
  },
  {
    name: '米白',
    hex: '#FAF8F0',
    rgb: '250,248,240',
    category: 'white',
    poem: '白云生处有人家，停车坐爱枫林晚',
    source: '《山行》· 杜牧',
    note: '稻米脱壳之色，温暖家常',
  },
  {
    name: '玉白',
    hex: '#F0F0F5',
    rgb: '240,240,245',
    category: 'white',
    poem: '玉碗盛来琥珀光，但使主人能醉客',
    source: '《客中行》· 李白',
    note: '羊脂白玉之色，君子比德于玉',
  },
  {
    name: '缟色',
    hex: '#F5F0E8',
    rgb: '245,240,232',
    category: 'white',
    poem: '素缟谁家子，翻飞不自持',
    source: '《白头吟》· 无名氏',
    note: '白色绢帛，《诗经》名物',
  },
  {
    name: '雪白',
    hex: '#FFFFFF',
    rgb: '255,255,255',
    category: 'white',
    poem: '梅须逊雪三分白，雪却输梅一段香',
    source: '《雪梅》· 卢梅坡',
    note: '白雪之色，纯粹无瑕',
  },
  {
    name: '银白',
    hex: '#E8E8F0',
    rgb: '232,232,240',
    category: 'white',
    poem: '银烛秋光冷画屏，轻罗小扇扑流萤',
    source: '《秋夕》· 杜牧',
    note: '白银河光，冷艳清丽',
  },
  {
    name: '铅白',
    hex: '#E0E0E5',
    rgb: '224,224,229',
    category: 'white',
    poem: '白骨露于野，千里无鸡鸣',
    source: '《蒿里行》· 曹操',
    note: '铅粉制白，古代女子敷面用',
  },
  {
    name: '鱼肚白',
    hex: '#E8ECF0',
    rgb: '232,236,240',
    category: 'white',
    poem: '天际霞光入水中，水中天际一时红',
    source: '《晓日》· 韩偓',
    note: '鱼腹之色，黎明破晓',
  },
  {
    name: '茧色',
    hex: '#F0E8D8',
    rgb: '240,232,216',
    category: 'white',
    poem: '春蚕到死丝方尽，蜡炬成灰泪始干',
    source: '《无题》· 李商隐',
    note: '蚕茧本色，淡黄偏白',
  },
  {
    name: '羽白',
    hex: '#F2F0EC',
    rgb: '242,240,236',
    category: 'white',
    poem: '西风残照，汉家陵阙',
    source: '《忆秦娥》· 李白',
    note: '鸟羽初生之白，柔软轻盈',
  },

  // ══════════════════════════════════════════════════════
  // 【柒·玄黑色系】玄之又玄，众妙之门
  // 《说文》："黑，火所熏之色也。"
  // ══════════════════════════════════════════════════════

  {
    name: '墨色',
    hex: '#1A1A1A',
    rgb: '26,26,26',
    category: 'black',
    poem: '黑云压城城欲摧，甲光向日金鳞开',
    source: '《雁门太守行》· 李贺',
    note: '松烟制墨，中国画根基之色',
  },
  {
    name: '玄色',
    hex: '#2B2B2B',
    rgb: '43,43,43',
    category: 'black',
    poem: '玄都观里桃千树，尽是刘郎去后栽',
    source: '《玄都观桃花》· 刘禹锡',
    note: '天际幽玄之色，五色之首',
  },
  {
    name: '乌黑',
    hex: '#1C1C1C',
    rgb: '28,28,28',
    category: 'black',
    poem: '乌啼隐杨花，醉卧沙场君莫笑',
    source: '《凉州词》· 王翰',
    note: '乌鸦羽色，纯黑发亮',
  },
  {
    name: '皂色',
    hex: '#3A3A3A',
    rgb: '58,58,58',
    category: 'black',
    poem: '皂雕寒始急，天马老能娇',
    source: '《遣闷戏呈路十九曹长》· 杜甫',
    note: '皂荚制黑色，唐宋皂衣为下层服色',
  },
  {
    name: '缁色',
    hex: '#2D2D2D',
    rgb: '45,45,45',
    category: 'black',
    poem: '缁衣之宜兮，敝予又改为兮',
    source: '《诗经·郑风》',
    note: '黑色帛，僧道服色，出世之相',
  },
  {
    name: '漆黑',
    hex: '#151515',
    rgb: '21,21,21',
    category: 'black',
    poem: '夜深不知天在水，满船清梦压星河',
    source: '《题龙阳县青草湖》· 唐珙',
    note: '极深之黑，如漆涂物',
  },
  {
    name: '煤黑',
    hex: '#1F1F1F',
    rgb: '31,31,31',
    category: 'black',
    poem: '黑云翻墨未遮山，白雨跳珠乱入船',
    source: '《六月二十七日望湖楼醉书》· 苏轼',
    note: '煤炭之色，厚重沉郁',
  },
  {
    name: '螺青',
    hex: '#2A3A3A',
    rgb: '42,58,58',
    category: 'black',
    poem: '青箬笠，绿蓑衣，斜风细雨不须归',
    source: '《渔歌子》· 张志和',
    note: '螺壳内壁之青黑，渔父意象',
  },
  {
    name: '黑褐',
    hex: '#3D2B1F',
    rgb: '61,43,31',
    category: 'black',
    poem: '须晴日，看红装素裹，分外妖娆',
    source: '《沁园春·雪》· 毛泽东',
    note: '黑土之色，褐中带黑',
  },
  {
    name: '烟黑',
    hex: '#1A1A1A',
    rgb: '26,26,26',
    category: 'black',
    poem: '烟涛微茫信难求，云霞明灭或可睹',
    source: '《梦游天姥吟留别》· 李白',
    note: '炊烟之色，飘渺幽远',
  },
  {
    name: '黑青',
    hex: '#2A2A2A',
    rgb: '42,42,42',
    category: 'black',
    poem: '黑云翻墨未遮山，白雨跳珠乱入船',
    source: '《六月二十七日望湖楼醉书》· 苏轼',
    note: '极深的青黑色，近乎墨',
  },

  // ══════════════════════════════════════════════════════
  // 【捌·矿物金石色】天地精华，丹青永固
  // 敦煌壁画、宋画、明清缂丝常用矿物颜料
  // ══════════════════════════════════════════════════════

  {
    name: '石青',
    hex: '#3A6B9B',
    rgb: '58,107,155',
    category: 'mineral',
    poem: '山泼黛，水挼蓝，翠相搀',
    source: '《诉衷情》· 黄庭坚',
    note: '蓝铜矿研磨，敦煌壁画主色，千年不褪',
  },
  {
    name: '石绿',
    hex: '#4A8C5E',
    rgb: '74,140,94',
    category: 'mineral',
    poem: '山回路转不见君，雪山空留马行处',
    source: '《白雪歌送武判官归京》· 岑参',
    note: '孔雀石研磨，与石青并称"两绿"',
  },
  {
    name: '石黄',
    hex: '#E8B040',
    rgb: '232,176,64',
    category: 'mineral',
    poem: '黄金白羽黄鹄飞，少年意气何时归',
    source: '《少年行》· 李白',
    note: '雌黄矿物，国画黄色颜料之尊',
  },
  {
    name: '赭石',
    hex: '#B5483A',
    rgb: '181,72,58',
    category: 'mineral',
    poem: '半卷红旗临易水，霜重鼓寒声不起',
    source: '《雁门太守行》· 李贺',
    note: '赤铁矿研磨，壁画人物肤色',
  },
  {
    name: '土朱',
    hex: '#C24B40',
    rgb: '194,75,64',
    category: 'mineral',
    poem: '朱门酒肉臭，路有冻死骨',
    source: '《自京赴奉先县咏怀五百字》· 杜甫',
    note: '赤铁矿之精者，画院专用',
  },
  {
    name: '铅丹',
    hex: '#D45030',
    rgb: '212,80,48',
    category: 'mineral',
    poem: '丹砂作尾耀明月，羽人仿佛从中来',
    source: '《飞龙引》· 李白',
    note: '四氧化三铅，敦煌壁画红唇用色',
  },
  {
    name: '铅白',
    hex: '#E0E0E5',
    rgb: '224,224,229',
    category: 'mineral',
    poem: '白骨露于野，千里无鸡鸣',
    source: '《蒿里行》· 曹操',
    note: '碱式碳酸铅，古代仕女敷面',
  },
  {
    name: '云母',
    hex: '#E8E0D0',
    rgb: '232,224,208',
    category: 'mineral',
    poem: '云母屏风烛影深，长河渐落晓星沉',
    source: '《嫦娥》· 李商隐',
    note: '白云母碎片色，画中闪光效果',
  },
  {
    name: '金箔',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'mineral',
    poem: '金碧山水照光辉，茅茨竹榻长幽微',
    source: '《题画》· 无名氏',
    note: '真金锤箔，佛像、建筑贴金',
  },
  {
    name: '银箔',
    hex: '#C8C8D0',
    rgb: '200,200,208',
    category: 'mineral',
    poem: '银烛秋光冷画屏，轻罗小扇扑流萤',
    source: '《秋夕》· 杜牧',
    note: '白银锤箔，装饰用，氧化后变黑',
  },
  {
    name: '雌黄',
    hex: '#E8B840',
    rgb: '232,184,64',
    category: 'mineral',
    poem: '信口雌黄误折旋，忠言逆耳无人识',
    source: '《感寓》· 无名氏',
    note: '矿物颜料，古代改字用"信口雌黄"',
  },
  {
    name: '雄黄',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'mineral',
    poem: '黄金白羽黄鹄飞，少年意气何时归',
    source: '《少年行》· 李白',
    note: '硫化砷，端午涂额辟邪，染纸不蛀',
  },
  {
    name: '砒石',
    hex: '#B03020',
    rgb: '176,48,32',
    category: 'mineral',
    poem: '朱砂砚里忽然红，信手拈来总是空',
    source: '《墨》· 无名氏',
    note: '砒霜原料，古代炼丹色',
  },
  {
    name: '紫矿',
    hex: '#8B3A5A',
    rgb: '139,58,90',
    category: 'mineral',
    poem: '紫袖红弦明月中，自弹自感闇低容',
    source: '《夜筝》· 白居易',
    note: '紫矿树胶制，藏传佛教颜料',
  },

  // ══════════════════════════════════════════════════════
  // 【玖·诗词意象色】以诗为色，意象万千
  // 古典诗词中反复出现的自然意象之色
  // ══════════════════════════════════════════════════════

  {
    name: '桃花粉',
    hex: '#F0A0B0',
    rgb: '240,160,176',
    category: 'imagery',
    poem: '人间四月芳菲尽，山寺桃花始盛开',
    source: '《大林寺桃花》· 白居易',
    note: '桃之夭夭，灼灼其华，春之使者',
  },
  {
    name: '柳烟绿',
    hex: '#8DB255',
    rgb: '141,178,85',
    category: 'imagery',
    poem: '渭城朝雨浥轻尘，客舍青青柳色新',
    source: '《送元二使安西》· 王维',
    note: '早春柳芽新发，烟霭蒙蒙',
  },
  {
    name: '杏花雨',
    hex: '#E8C0B0',
    rgb: '232,192,176',
    category: 'imagery',
    poem: '小楼一夜听春雨，深巷明朝卖杏花',
    source: '《临安春雨初霁》· 陆游',
    note: '杏花春雨，江南二月',
  },
  {
    name: '梨花白',
    hex: '#F5F0F0',
    rgb: '245,240,240',
    category: 'imagery',
    poem: '忽如一夜春风来，千树万树梨花开',
    source: '《白雪歌送武判官归京》· 岑参',
    note: '以梨花喻雪，洁白如雪',
  },
  {
    name: '梅花雪',
    hex: '#F8F0F4',
    rgb: '248,240,244',
    category: 'imagery',
    poem: '梅须逊雪三分白，雪却输梅一段香',
    source: '《雪梅》· 卢梅坡',
    note: '寒梅傲雪，幽香沁人',
  },
  {
    name: '桂月黄',
    hex: '#E8C050',
    rgb: '232,192,80',
    category: 'imagery',
    poem: '中庭地白树栖鸦，冷露无声湿桂花',
    source: '《十五夜望月》· 王建',
    note: '八月桂花香，月下金黄',
  },
  {
    name: '荷风红',
    hex: '#E8607A',
    rgb: '232,96,122',
    category: 'imagery',
    poem: '接天莲叶无穷碧，映日荷花别样红',
    source: '《晓出净慈寺送林子方》· 杨万里',
    note: '映日荷花，别样鲜红',
  },
  {
    name: '枫林红',
    hex: '#C84030',
    rgb: '200,64,48',
    category: 'imagery',
    poem: '停车坐爱枫林晚，霜叶红于二月花',
    source: '《山行》· 杜牧',
    note: '霜降枫叶，艳于春花',
  },
  {
    name: '芦花白',
    hex: '#E8E0D0',
    rgb: '232,224,208',
    category: 'imagery',
    poem: '蒹葭苍苍，白露为霜',
    source: '《诗经·蒹葭》',
    note: '芦苇秋花，蒹葭苍茫',
  },
  {
    name: '杨花白',
    hex: '#E8E8E0',
    rgb: '232,232,224',
    category: 'imagery',
    poem: '杨花落尽子规啼，闻道龙标过五溪',
    source: '《闻王昌龄左迁龙标遥有此寄》· 李白',
    note: '柳絮随风，春暮飘零',
  },
  {
    name: '杏叶黄',
    hex: '#E8A840',
    rgb: '232,168,64',
    category: 'imagery',
    poem: '霜降水返壑，风落木归山',
    source: '《岁晚》· 白居易',
    note: '秋日杏叶，金黄满地',
  },
  {
    name: '桐叶绿',
    hex: '#5A9A60',
    rgb: '90,154,96',
    category: 'imagery',
    poem: '春风桃李花开日，秋雨梧桐叶落时',
    source: '《长恨歌》· 白居易',
    note: '梧桐秋雨，愁思绵绵',
  },
  {
    name: '芭蕉绿',
    hex: '#5A8A50',
    rgb: '90,138,80',
    category: 'imagery',
    poem: '窗前谁种芭蕉树，阴满中庭',
    source: '《添字丑奴儿》· 李清照',
    note: '芭蕉听雨，绿意盎然',
  },
  {
    name: '槐花黄',
    hex: '#E8C860',
    rgb: '232,200,96',
    category: 'imagery',
    poem: '槐绿橙黄正好时，深红皱绿斗成姿',
    source: '《暮春》· 无名氏',
    note: '五月槐花香，满城金黄',
  },
  {
    name: '榆钱绿',
    hex: '#8DB260',
    rgb: '141,178,96',
    category: 'imagery',
    poem: '城中桃李须臾尽，争似垂杨地代新',
    source: '《杨柳枝》· 刘禹锡',
    note: '榆树翅果成串，翠绿如钱',
  },
  {
    name: '牡丹红',
    hex: '#C84060',
    rgb: '200,64,96',
    category: 'imagery',
    poem: '唯有牡丹真国色，花开时节动京城',
    source: '《赏牡丹》· 刘禹锡',
    note: '国色天香，倾国倾城',
  },
  {
    name: '海棠红',
    hex: '#E07080',
    rgb: '224,112,128',
    category: 'imagery',
    poem: '枝间新绿一重重，小蕾深藏数点红',
    source: '《同儿辈赋未开海棠》· 元好问',
    note: '海棠春睡，娇羞欲滴',
  },
  {
    name: '丁香紫',
    hex: '#9B70A0',
    rgb: '155,112,160',
    category: 'imagery',
    poem: '青鸟不传云外信，丁香空结雨中愁',
    source: '《浣溪沙》· 李璟',
    note: '丁香结愁，雨中紫色',
  },
  {
    name: '菊花黄',
    hex: '#D9A435',
    rgb: '217,164,53',
    category: 'imagery',
    poem: '采菊东篱下，悠然见南山',
    source: '《饮酒》· 陶渊明',
    note: '东篱采菊，隐逸之象征',
  },
  {
    name: '茶绿',
    hex: '#5A8A4A',
    rgb: '90,138,74',
    category: 'imagery',
    poem: '茶能散闷将愁去，茶送来香入梦来',
    source: '《茶》· 无名氏',
    note: '茶山新绿，春日胜景',
  },

  // ══════════════════════════════════════════════════════
  // 【拾·二十四节气色】岁时流转，天地换色
  // 节气之名本身即是最美的颜色
  // ══════════════════════════════════════════════════════

  {
    name: '立春·新绿',
    hex: '#8DB255',
    rgb: '141,178,85',
    category: 'solar',
    poem: '春风又绿江南岸，明月何时照我还',
    source: '《泊船瓜洲》· 王安石',
    note: '立春：万物复苏，第一抹新绿',
  },
  {
    name: '雨水·草青',
    hex: '#7CB342',
    rgb: '124,179,66',
    category: 'solar',
    poem: '天街小雨润如酥，草色遥看近却无',
    source: '《早春呈水部张十八员外》· 韩愈',
    note: '雨水：酥雨润土，草色初萌',
  },
  {
    name: '惊蛰·春雷',
    hex: '#6B8EAD',
    rgb: '107,142,173',
    category: 'solar',
    poem: '微雨众卉新，一雷惊蛰始',
    source: '《田家》· 韦应物',
    note: '惊蛰：春雷惊醒万物，天色渐暖',
  },
  {
    name: '春分·柳青',
    hex: '#7CB342',
    rgb: '124,179,66',
    category: 'solar',
    poem: '春城无处不飞花，寒食东风御柳斜',
    source: '《寒食》· 韩翃',
    note: '春分：昼夜平分，杨柳依依',
  },
  {
    name: '清明·桐华',
    hex: '#E8A0A0',
    rgb: '232,160,160',
    category: 'solar',
    poem: '清明时节雨纷纷，路上行人欲断魂',
    source: '《清明》· 杜牧',
    note: '清明：桐华初放，春和景明',
  },
  {
    name: '谷雨·萍绿',
    hex: '#4A8C5E',
    rgb: '74,140,94',
    category: 'solar',
    poem: '谷雨如丝复似尘，煮瓶浮蜡正尝新',
    source: '《春中途中寄南巴崔使君》· 周朴',
    note: '谷雨：浮萍始生，雨生百谷',
  },
  {
    name: '立夏·槐黄',
    hex: '#E8C860',
    rgb: '232,200,96',
    category: 'solar',
    poem: '四月清和雨乍晴，南山当户转分明',
    source: '《客中初夏》· 司马光',
    note: '立夏：槐花金黄，夏日初长',
  },
  {
    name: '小满·穗黄',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'solar',
    poem: '夜来南风起，小麦覆陇黄',
    source: '《观麦》· 白居易',
    note: '小满：麦穗灌浆，渐趋饱满',
  },
  {
    name: '芒种·金黄',
    hex: '#DAA520',
    rgb: '218,165,32',
    category: 'solar',
    poem: '锄禾日当午，汗滴禾下土',
    source: '《悯农》· 李绅',
    note: '芒种：麦收在即，满地金黄',
  },
  {
    name: '夏至·莲红',
    hex: '#E8607A',
    rgb: '232,96,122',
    category: 'solar',
    poem: '接天莲叶无穷碧，映日荷花别样红',
    source: '《晓出净慈寺送林子方》· 杨万里',
    note: '夏至：莲荷盛开，阳气至极',
  },
  {
    name: '小暑·荷风',
    hex: '#5DAE8B',
    rgb: '93,174,139',
    category: 'solar',
    poem: '水光潋滟晴方好，山色空蒙雨亦奇',
    source: '《饮湖上初晴后雨》· 苏轼',
    note: '小暑：暑气初生，荷风送香',
  },
  {
    name: '大暑·赤炎',
    hex: '#E05030',
    rgb: '224,80,48',
    category: 'solar',
    poem: '赤日炎炎似火烧，野田禾稻半枯焦',
    source: '《悯农》· 李绅',
    note: '大暑：一年最热，骄阳似火',
  },
  {
    name: '立秋·梧黄',
    hex: '#D4A030',
    rgb: '212,160,48',
    category: 'solar',
    poem: '银烛秋光冷画屏，轻罗小扇扑流萤',
    source: '《秋夕》· 杜牧',
    note: '立秋：梧桐叶落，一叶知秋',
  },
  {
    name: '处暑·露白',
    hex: '#E8E8F0',
    rgb: '232,232,240',
    category: 'solar',
    poem: '露从今夜白，月是故乡明',
    source: '《月夜忆舍弟》· 杜甫',
    note: '处暑：白露初降，暑气渐消',
  },
  {
    name: '白露·蒹白',
    hex: '#E8E0D0',
    rgb: '232,224,208',
    category: 'solar',
    poem: '蒹葭苍苍，白露为霜，所谓伊人，在水一方',
    source: '《诗经·蒹葭》',
    note: '白露：水汽凝结，秋意渐浓',
  },
  {
    name: '秋分·桂金',
    hex: '#E8C050',
    rgb: '232,192,80',
    category: 'solar',
    poem: '中庭地白树栖鸦，冷露无声湿桂花',
    source: '《十五夜望月》· 王建',
    note: '秋分：桂香满城，昼夜平分',
  },
  {
    name: '寒露·枫丹',
    hex: '#C84030',
    rgb: '200,64,48',
    category: 'solar',
    poem: '停车坐爱枫林晚，霜叶红于二月花',
    source: '《山行》· 杜牧',
    note: '寒露：枫叶霜红，秋深露寒',
  },
  {
    name: '霜降·柿红',
    hex: '#D45030',
    rgb: '212,80,48',
    category: 'solar',
    poem: '柿叶翻红霜景秋，碧天如水倚红楼',
    source: '《秋凉闲卧》· 白居易',
    note: '霜降：柿子熟透，满树红妆',
  },
  {
    name: '立冬·枯褐',
    hex: '#8B6040',
    rgb: '139,96,64',
    category: 'solar',
    poem: '秋风吹尽旧庭柯，黄叶丹枫客里过',
    source: '《秋冬之交》· 无名氏',
    note: '立冬：草木枯黄，万物收藏',
  },
  {
    name: '小雪·凝白',
    hex: '#E8ECF0',
    rgb: '232,236,240',
    category: 'solar',
    poem: '小雪已晴芦叶暗，长波乍急鹤声嘶',
    source: '《夜泊荆溪》· 陈羽',
    note: '小雪：初雪降临，天地苍茫',
  },
  {
    name: '大雪·雪白',
    hex: '#FFFFFF',
    rgb: '255,255,255',
    category: 'solar',
    poem: '千山鸟飞绝，万径人踪灭',
    source: '《江雪》· 柳宗元',
    note: '大雪：雪深三尺，天地一白',
  },
  {
    name: '冬至·墨灰',
    hex: '#3A3A3A',
    rgb: '58,58,58',
    category: 'solar',
    poem: '天时人事日相催，冬至阳生春又来',
    source: '《小至》· 杜甫',
    note: '冬至：夜最长，阴阳交替',
  },
  {
    name: '小寒·霜白',
    hex: '#EEF0F5',
    rgb: '238,240,245',
    category: 'solar',
    poem: '霜鹰近北首，雊雉隐丛茅',
    source: '《小寒》· 元稹',
    note: '小寒：冰霜始凝，寒气渐盛',
  },
  {
    name: '大寒·暮墨',
    hex: '#1C1C1C',
    rgb: '28,28,28',
    category: 'solar',
    poem: '大寒须守火，无事莫出门',
    source: '《大寒》· 陆游',
    note: '大寒：一年最冷，寒至极处',
  },

  // ══════════════════════════════════════════════════════
  // 【拾壹·地方志色】一方水土，一方色彩
  // 参照《天工开物·彰施》《苏州丝绸志》《敦煌壁画色谱》
  // ══════════════════════════════════════════════════════

  {
    name: '苏州梅',
    hex: '#E07090',
    rgb: '224,112,144',
    category: 'imagery',
    poem: '梅子黄时日日晴，小溪泛尽却山行',
    source: '《三衢道中》· 曾几',
    note: '苏州水乡梅子黄熟之色，江南初夏',
  },
  {
    name: '苏绣红',
    hex: '#C02050',
    rgb: '192,32,80',
    category: 'imagery',
    poem: '遍身罗绮者，不是养蚕人',
    source: '《蚕妇》· 张俞',
    note: '苏州刺绣正红，配金线为皇家贡品',
  },
  {
    name: '湘绣蓝',
    hex: '#2A5A9B',
    rgb: '42,90,155',
    category: 'imagery',
    poem: '斑竹一枝千滴泪，红霞万朵百重衣',
    source: '《七律·答友人》· 毛泽东',
    note: '湖南湘绣传统蓝，绣蝴蝶用此色',
  },
  {
    name: '蜀锦朱',
    hex: '#C03040',
    rgb: '192,48,64',
    category: 'imagery',
    poem: '晓看红湿处，花重锦官城',
    source: '《春夜喜雨》· 杜甫',
    note: '成都蜀锦朱红，千年传承',
  },
  {
    name: '云锦金',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'imagery',
    poem: '锦江春色来天地，玉垒浮云变古今',
    source: '《登楼》· 杜甫',
    note: '南京云锦织金，金线与妆花并用',
  },
  {
    name: '缂丝驼',
    hex: '#B89060',
    rgb: '184,144,96',
    category: 'imagery',
    poem: '大漠孤烟直，长河落日圆',
    source: '《使至塞上》· 王维',
    note: '缂丝驼色，唐代织品主色',
  },
  {
    name: '藏毯赭',
    hex: '#8B5A3A',
    rgb: '139,90,58',
    category: 'imagery',
    poem: '黄河远上白云间，一片孤城万仞山',
    source: '《凉州词》· 王之涣',
    note: '藏族织毯赭色，牦牛毛本色',
  },
  {
    name: '苗绣靛',
    hex: '#1E3A6B',
    rgb: '30,58,107',
    category: 'imagery',
    poem: '蓝靛染裙春已深，嫁得黔娄未嫁时',
    source: '《古意》· 无名氏',
    note: '苗族蜡染靛蓝，蜡刀画蜡，古法不传',
  },
  {
    name: '壮锦青',
    hex: '#2D5A4A',
    rgb: '45,90,74',
    category: 'imagery',
    poem: '青箬笠，绿蓑衣，斜风细雨不须归',
    source: '《渔歌子》· 张志和',
    note: '壮锦传统青，壮族织锦用棉线配色',
  },
  {
    name: '闽南砖',
    hex: '#8B4030',
    rgb: '139,64,48',
    category: 'imagery',
    poem: '春风不度玉门关，万里长城砖石寒',
    source: '《凉州词》· 王之涣',
    note: '闽南红砖古厝之色，蚵壳厝特色',
  },
  {
    name: '徽州墨',
    hex: '#1A1A1A',
    rgb: '26,26,26',
    category: 'imagery',
    poem: '水墨徽州画不成，粉墙黛瓦雨声声',
    source: '《徽州》· 无名氏',
    note: '徽派建筑白墙黑瓦，水墨之乡',
  },
  {
    name: '京红',
    hex: '#B82030',
    rgb: '184,32,48',
    category: 'imagery',
    poem: '朱门酒肉臭，路有冻死骨',
    source: '《自京赴奉先县咏怀五百字》· 杜甫',
    note: '北京故宫红墙之色，皇家气势',
  },
  {
    name: '宫黄',
    hex: '#E8B840',
    rgb: '232,184,64',
    category: 'imagery',
    poem: '五步一楼，十步一阁，廊腰缦回，檐牙高啄',
    source: '《阿房宫赋》· 杜牧',
    note: '故宫琉璃瓦黄，帝王专属',
  },
  {
    name: '琉璃蓝',
    hex: '#3A6B9B',
    rgb: '58,107,155',
    category: 'imagery',
    poem: '蓝田日暖玉生烟，此情可待成追忆',
    source: '《锦瑟》· 李商隐',
    note: '故宫黄蓝琉璃，彩画配色',
  },
  {
    name: '官绿',
    hex: '#3A7A50',
    rgb: '58,122,80',
    category: 'imagery',
    poem: '绿蚁新醅酒，红泥小火炉',
    source: '《问刘十九》· 白居易',
    note: '宋代官服绿，官员品级之色',
  },
  {
    name: '石绿',
    hex: '#4A8C5E',
    rgb: '74,140,94',
    category: 'imagery',
    poem: '山回路转不见君，雪山空留马行处',
    source: '《白雪歌送武判官归京》· 岑参',
    note: '敦煌壁画石绿，宋画山石主色',
  },
  {
    name: '烟翠',
    hex: '#4A8A70',
    rgb: '74,138,112',
    category: 'imagery',
    poem: '烟雨莽苍苍，龟蛇锁大江',
    source: '《菩萨蛮·黄鹤楼》· 毛泽东',
    note: '烟雨朦胧之翠，山水画常用',
  },
  {
    name: '暮山紫',
    hex: '#6B5A8C',
    rgb: '107,90,140',
    category: 'imagery',
    poem: '山映斜阳天接水，芳草无情，更在斜阳外',
    source: '《苏幕遮》· 范仲淹',
    note: '暮色中山峦之紫，水墨留白',
  },
  {
    name: '晚霞红',
    hex: '#E86840',
    rgb: '232,104,64',
    category: 'imagery',
    poem: '落霞与孤鹜齐飞，秋水共长天一色',
    source: '《滕王阁序》· 王勃',
    note: '晚霞满天之色，一天中最绚烂',
  },
  {
    name: '晓风绿',
    hex: '#5A9A70',
    rgb: '90,154,112',
    category: 'imagery',
    poem: '杨柳岸，晓风残月',
    source: '《雨霖铃》· 柳永',
    note: '拂晓微风之绿，清冷温柔',
  },

  // ══════════════════════════════════════════════════════
  // 【拾贰·雨烟霞云雾色】天地气韵，无形之色
  // 古典诗词中以自然气象为色的意象
  // ══════════════════════════════════════════════════════

  {
    name: '烟雨青',
    hex: '#5A7A80',
    rgb: '90,122,128',
    category: 'imagery',
    poem: '南朝四百八十寺，多少楼台烟雨中',
    source: '《江南春》· 杜牧',
    note: '江南烟雨，迷蒙青灰',
  },
  {
    name: '杏花烟',
    hex: '#8A7A88',
    rgb: '138,122,136',
    category: 'imagery',
    poem: '杏花春雨江南，芳草萋萋鹦鹉洲',
    source: '《风入松》· 虞集',
    note: '杏花春雨，烟岚笼罩',
  },
  {
    name: '山岚色',
    hex: '#6A8A88',
    rgb: '106,138,136',
    category: 'imagery',
    poem: '山色空蒙雨亦奇，水光潋滟晴方好',
    source: '《饮湖上初晴后雨》· 苏轼',
    note: '山间雾气，青中带灰',
  },
  {
    name: '云山蓝',
    hex: '#6A8AAC',
    rgb: '106,138,172',
    category: 'imagery',
    poem: '荡胸生层云，决眦入归鸟',
    source: '《望岳》· 杜甫',
    note: '云锁山头，蓝中透白',
  },
  {
    name: '云母白',
    hex: '#E8E8F0',
    rgb: '232,232,240',
    category: 'imagery',
    poem: '云母屏风烛影深，长河渐落晓星沉',
    source: '《嫦娥》· 李商隐',
    note: '云母薄片透光，如云似月',
  },
  {
    name: '朝霞丹',
    hex: '#E87860',
    rgb: '232,120,96',
    category: 'imagery',
    poem: '朝辞白帝彩云间，千里江陵一日还',
    source: '《早发白帝城》· 李白',
    note: '朝霞如火，一日之始',
  },
  {
    name: '暮霞紫',
    hex: '#C86090',
    rgb: '200,96,144',
    category: 'imagery',
    poem: '夕阳无限好，只是近黄昏',
    source: '《乐游原》· 李商隐',
    note: '暮色霞光，紫中带红',
  },
  {
    name: '残霞红',
    hex: '#D87060',
    rgb: '216,112,96',
    category: 'imagery',
    poem: '雨歇晚霞明，风调夜景清',
    source: '《秋晚》· 无名氏',
    note: '雨后残霞，暗红将暮',
  },
  {
    name: '晨雾白',
    hex: '#E8ECF0',
    rgb: '232,236,240',
    category: 'imagery',
    poem: '雾失楼台，月迷津渡，桃源望断无寻处',
    source: '《踏莎行》· 秦观',
    note: '晨雾弥漫，白茫茫一片',
  },
  {
    name: '江雾蓝',
    hex: '#8AAABB',
    rgb: '138,170,187',
    category: 'imagery',
    poem: '春江潮水连海平，海上明月共潮生',
    source: '《春江花月夜》· 张若虚',
    note: '江面雾气，朦胧幽蓝',
  },
  {
    name: '松雾绿',
    hex: '#5A8A78',
    rgb: '90,138,120',
    category: 'imagery',
    poem: '松风吹解带，山月照弹琴',
    source: '《酬张少府》· 王维',
    note: '松林雾岚，深绿带灰',
  },
  {
    name: '夜雨青',
    hex: '#4A6A70',
    rgb: '74,106,112',
    category: 'imagery',
    poem: '夜阑卧听风吹雨，铁马冰河入梦来',
    source: '《十一月四日风雨大作》· 陆游',
    note: '夜雨潇潇，青黑暗凉',
  },
  {
    name: '春雨绿',
    hex: '#6A9A68',
    rgb: '106,154,104',
    category: 'imagery',
    poem: '好雨知时节，当春乃发生',
    source: '《春夜喜雨》· 杜甫',
    note: '春雨润物，绿意盎然',
  },
  {
    name: '秋雨灰',
    hex: '#7A8A88',
    rgb: '122,138,136',
    category: 'imagery',
    poem: '君问归期未有期，巴山夜雨涨秋池',
    source: '《夜雨寄北》· 李商隐',
    note: '秋雨绵绵，灰凉低沉',
  },
  {
    name: '檐下雨',
    hex: '#8A8A8A',
    rgb: '138,138,138',
    category: 'imagery',
    poem: '何当共剪西窗烛，却话巴山夜雨时',
    source: '《夜雨寄北》· 李商隐',
    note: '檐下滴雨，灰白连绵',
  },
  {
    name: '清明雨',
    hex: '#7A8A7A',
    rgb: '122,138,122',
    category: 'imagery',
    poem: '清明时节雨纷纷，路上行人欲断魂',
    source: '《清明》· 杜牧',
    note: '清明时节，细雨蒙蒙',
  },
  {
    name: '黄梅雨',
    hex: '#9A9A70',
    rgb: '154,154,112',
    category: 'imagery',
    poem: '黄梅时节家家雨，青草池塘处处蛙',
    source: '《约客》· 赵师秀',
    note: '黄梅天雨，闷热潮湿',
  },
  {
    name: '梧桐雨',
    hex: '#6A6050',
    rgb: '106,96,80',
    category: 'imagery',
    poem: '梧桐更兼细雨，到黄昏、点点滴滴',
    source: '《声声慢》· 李清照',
    note: '梧桐叶上雨滴，最惹愁思',
  },
  {
    name: '白雨色',
    hex: '#B0B0B0',
    rgb: '176,176,176',
    category: 'imagery',
    poem: '黑云翻墨未遮山，白雨跳珠乱入船',
    source: '《六月二十七日望湖楼醉书》· 苏轼',
    note: '白雨（夏日阵雨）如珠，骤然倾盆',
  },

  // ══════════════════════════════════════════════════════
  // 【拾叁·少数民族色】锦绣中华，多彩交融
  // 参照苗族蜡染、壮族织锦、藏族唐卡、维吾尔族织毯配色
  // ══════════════════════════════════════════════════════

  {
    name: '苗蜡靛',
    hex: '#1A3A8B',
    rgb: '26,58,139',
    category: 'imagery',
    poem: '蓝靛从教千百遍，染将春色上罗衣',
    source: '《苗女》· 无名氏',
    note: '苗族蜡染靛蓝，蜡刀防染，古法传承',
  },
  {
    name: '苗红',
    hex: '#B82030',
    rgb: '184,32,48',
    category: 'imagery',
    poem: '红绣球，抛向谁家年少游',
    source: '《竹枝词》· 刘禹锡',
    note: '苗族刺绣正红，银饰相配',
  },
  {
    name: '壮锦黄',
    hex: '#D4A020',
    rgb: '212,160,32',
    category: 'imagery',
    poem: '金缕玉衣无处觅，绣旗犹卷旧山川',
    source: '《边城》· 无名氏',
    note: '壮锦用棉线挑织，黄色为基底',
  },
  {
    name: '藏红',
    hex: '#A01030',
    rgb: '160,16,48',
    category: 'imagery',
    poem: '红宫粉壁相映辉，梵唱经声入云端',
    source: '《布达拉宫》· 无名氏',
    note: '藏传佛教红，庄严神圣',
  },
  {
    name: '藏蓝',
    hex: '#1A3A7A',
    rgb: '26,58,122',
    category: 'imagery',
    poem: '青海长云暗雪山，孤城遥望玉门关',
    source: '《从军行》· 王昌龄',
    note: '唐卡藏蓝，与金色并用',
  },
  {
    name: '藏青',
    hex: '#1E3A5F',
    rgb: '30,58,95',
    category: 'imagery',
    poem: '蓝水远从千涧落，玉山高并两峰寒',
    source: '《九日蓝田崔氏庄》· 杜甫',
    note: '藏族服饰常见色，牦牛毛织',
  },
  {
    name: '蒙青',
    hex: '#2A4A7A',
    rgb: '42,74,122',
    category: 'imagery',
    poem: '天苍苍，野茫茫，风吹草低见牛羊',
    source: '《敕勒歌》· 北朝民歌',
    note: '蒙古草原天空之蓝，一望无际',
  },
  {
    name: '蒙白',
    hex: '#F0F0F0',
    rgb: '240,240,240',
    category: 'imagery',
    poem: '白草茫茫连沙漠，长风万里吹胡笳',
    source: '《边塞曲》· 无名氏',
    note: '蒙古包白毡，草原雪景',
  },
  {
    name: '回回红',
    hex: '#C03050',
    rgb: '192,48,80',
    category: 'imagery',
    poem: '春风不度玉门关，万里长征人未还',
    source: '《凉州词》· 王之涣',
    note: '维吾尔族喜欢红色，艾德莱斯绸主色',
  },
  {
    name: '回回蓝',
    hex: '#2A5A9A',
    rgb: '42,90,154',
    category: 'imagery',
    poem: '蓝蓝的天上飘白云，戈壁滩上无行人',
    source: '《新疆谣》· 无名氏',
    note: '维吾尔族蓝色，清真寺穹顶常见',
  },
  {
    name: '彝黑',
    hex: '#1A1A1A',
    rgb: '26,26,26',
    category: 'imagery',
    poem: '黑漆漆的夜，星子也无光',
    source: '《彝山谣》· 无名氏',
    note: '彝族尚黑，黑衣黑裤黑头帕',
  },
  {
    name: '彝红',
    hex: '#C82030',
    rgb: '200,32,48',
    category: 'imagery',
    poem: '红红的日子火把节，欢歌笑语满山岗',
    source: '《火把节》· 无名氏',
    note: '彝族火把节，红色象征热情',
  },
  {
    name: '傣锦绿',
    hex: '#2A7A50',
    rgb: '42,122,80',
    category: 'imagery',
    poem: '傣家竹楼绿荫里，孔雀开屏春意浓',
    source: '《西双版纳》· 无名氏',
    note: '傣族织锦绿，热带雨林之色',
  },
  {
    name: '白族蓝',
    hex: '#3A6A9A',
    rgb: '58,106,154',
    category: 'imagery',
    poem: '苍山不墨千秋画，洱海无弦万古琴',
    source: '《大理》· 无名氏',
    note: '白族扎染蓝，苍山洱海之色',
  },
  {
    name: '白族白',
    hex: '#F8F8F8',
    rgb: '248,248,248',
    category: 'imagery',
    poem: '三坊一照壁，四合五天井，白墙青瓦映蓝天',
    source: '《白族民居》· 无名氏',
    note: '白族建筑白墙，青瓦蓝天',
  },
  {
    name: '土家锦',
    hex: '#A82040',
    rgb: '168,32,64',
    category: 'imagery',
    poem: '武陵深处有人家，织女机杼响咿呀',
    source: '《土家》· 无名氏',
    note: '土家族西兰卡普，红黑为主',
  },
  {
    name: '纳西黑',
    hex: '#1C1C1C',
    rgb: '28,28,28',
    category: 'imagery',
    poem: '东巴文字象形古，黑衣披星月下读',
    source: '《纳西》· 无名氏',
    note: '纳西族尚黑，东巴文字黑色',
  },
  {
    name: '黎锦青',
    hex: '#2A6A50',
    rgb: '42,106,80',
    category: 'imagery',
    poem: '五指山上云雾深，黎锦织出彩虹色',
    source: '《黎族》· 无名氏',
    note: '黎族织锦，青色棉线为底',
  },

  // ══════════════════════════════════════════════════════
  // 【拾肆·五德里色】仁义礼智信，天地五行
  // 木青、火赤、土黄、金白、水黑
  // ══════════════════════════════════════════════════════

  {
    name: '仁·木青',
    hex: '#2A8A50',
    rgb: '42,138,80',
    category: 'green',
    poem: '仁者乐山，智者乐水',
    source: '《论语·雍也》',
    note: '木之德，生发仁爱，东方之色',
  },
  {
    name: '义·火赤',
    hex: '#C03030',
    rgb: '192,48,48',
    category: 'red',
    poem: '人生自古谁无死，留取丹心照汗青',
    source: '《过零丁洋》· 文天祥',
    note: '火之烈，照亮正义，南方之色',
  },
  {
    name: '礼·土黄',
    hex: '#C8A030',
    rgb: '200,160,48',
    category: 'yellow',
    poem: '礼之用，和为贵',
    source: '《论语·学而》',
    note: '土之厚，承载礼仪，中宫之色',
  },
  {
    name: '智·金白',
    hex: '#C8C8D0',
    rgb: '200,200,208',
    category: 'white',
    poem: '知之者不如好之者，好之者不如乐之者',
    source: '《论语·雍也》',
    note: '金之清，洞察明辨，西方之色',
  },
  {
    name: '信·水黑',
    hex: '#1A2A3A',
    rgb: '26,42,58',
    category: 'black',
    poem: '言必信，行必果',
    source: '《论语·子路》',
    note: '水之深，诚信如渊，北方之色',
  },

  // ══════════════════════════════════════════════════════
  // 【拾伍·岁时节令色】四时之序，天地之礼
  // 元日、上巳、端午、七夕、中秋、重阳
  // ══════════════════════════════════════════════════════

  {
    name: '元日红',
    hex: '#C02040',
    rgb: '192,32,64',
    category: 'imagery',
    poem: '爆竹声中一岁除，春风送暖入屠苏',
    source: '《元日》· 王安石',
    note: '春节红帖，桃符压岁，辞旧迎新',
  },
  {
    name: '上巳蓝',
    hex: '#4A8AAC',
    rgb: '74,138,172',
    category: 'imagery',
    poem: '三月三日天气新，长安水边多丽人',
    source: '《丽人行》· 杜甫',
    note: '上巳祓禊，春水沐浴，郊外踏青',
  },
  {
    name: '端午青',
    hex: '#3A8A60',
    rgb: '58,138,96',
    category: 'imagery',
    poem: '五月五日天晴明，杨花绕江啼晓莺',
    source: '《竞渡歌》· 张建封',
    note: '端午艾草，粽叶清香，龙舟竞渡',
  },
  {
    name: '七夕粉',
    hex: '#E8A0C0',
    rgb: '232,160,192',
    category: 'imagery',
    poem: '银烛秋光冷画屏，轻罗小扇扑流萤',
    source: '《秋夕》· 杜牧',
    note: '七夕乞巧，银河鹊桥，女儿心事',
  },
  {
    name: '中秋黄',
    hex: '#E8B840',
    rgb: '232,184,64',
    category: 'imagery',
    poem: '但愿人长久，千里共婵娟',
    source: '《水调歌头》· 苏轼',
    note: '中秋月圆，月饼金黄，阖家团圆',
  },
  {
    name: '重阳紫',
    hex: '#7B4A8C',
    rgb: '123,74,140',
    category: 'imagery',
    poem: '独在异乡为异客，每逢佳节倍思亲',
    source: '《九月九日忆山东兄弟》· 王维',
    note: '重阳登高，茱萸紫红，秋意渐深',
  },
  {
    name: '除夕金',
    hex: '#D4A017',
    rgb: '212,160,23',
    category: 'imagery',
    poem: '天地风霜尽，乾坤气象和，历添新岁月，灯火夜重开',
    source: '《守岁》· 董舜民',
    note: '除夕守岁，灯笼金红，万家灯火',
  },
  {
    name: '元宵白',
    hex: '#F0F0E0',
    rgb: '240,240,224',
    category: 'imagery',
    poem: '众里寻他千百度，蓦然回首，那人却在灯火阑珊处',
    source: '《青玉案·元夕》· 辛弃疾',
    note: '元宵灯火，汤圆雪白，花市如昼',
  },
  {
    name: '清明柳',
    hex: '#7CB342',
    rgb: '124,179,66',
    category: 'imagery',
    poem: '清明时节雨纷纷，路上行人欲断魂',
    source: '《清明》· 杜牧',
    note: '清明插柳，折柳赠别，追思先人',
  },
  {
    name: '寒食青',
    hex: '#4A8A60',
    rgb: '74,138,96',
    category: 'imagery',
    poem: '春城无处不飞花，寒食东风御柳斜',
    source: '《寒食》· 韩翃',
    note: '寒食禁火，新火未得，春寒料峭',
  },

  // ══════════════════════════════════════════════════════
  // 【拾陆·器物色】文房清供，君子四艺
  // 琴棋书画，茶酒瓷陶
  // ══════════════════════════════════════════════════════

  {
    name: '宣纸白',
    hex: '#FAF6F0',
    rgb: '250,246,240',
    category: 'white',
    poem: '纸田墨稼，其乐洋洋',
    source: '《笔势》· 无名氏',
    note: '宣纸产自安徽宣城，水墨氤氲',
  },
  {
    name: '松烟墨',
    hex: '#1A1A1A',
    rgb: '26,26,26',
    category: 'black',
    poem: '墨香一缕穿云起，写尽人间万古情',
    source: '《墨》· 无名氏',
    note: '松烟制墨，油灯燃松，烟炱凝聚',
  },
  {
    name: '砚台青',
    hex: '#4A5A60',
    rgb: '74,90,96',
    category: 'imagery',
    poem: '砚池水满墨花香，笔下风云自卷舒',
    source: '《文房》· 无名氏',
    note: '端砚石青，质细温润，发墨如油',
  },
  {
    name: '紫砂赭',
    hex: '#8B5A40',
    rgb: '139,90,64',
    category: 'imagery',
    poem: '茶香一盏沁心脾，紫瓯轻叩试新茶',
    source: '《茶具》· 无名氏',
    note: '宜兴紫砂，窑变赭色，泡茶不夺香',
  },
  {
    name: '青瓷色',
    hex: '#8AAC9B',
    rgb: '138,172,155',
    category: 'imagery',
    poem: '九秋风露越窑开，夺得千峰翠色来',
    source: '《贡余秘色茶盏》· 徐夤',
    note: '越窑青瓷，秘色如玉，千峰翠色',
  },
  {
    name: '建盏黑',
    hex: '#2A2A2A',
    rgb: '42,42,42',
    category: 'black',
    poem: '兔毫金饼相辉映，吃茶去也最清心',
    source: '《建盏》· 无名氏',
    note: '建窑兔毫盏，黑釉窑变，芒口铁胎',
  },
  {
    name: '汝窑天',
    hex: '#6A8AAC',
    rgb: '106,138,172',
    category: 'imagery',
    poem: '雨过天青云破处，这般颜色做将来',
    source: '《汝窑》· 传说宋徽宗',
    note: '汝窑天青，玛瑙入釉，蟹爪纹开片',
  },
  {
    name: '景德白',
    hex: '#F8F8F5',
    rgb: '248,248,245',
    category: 'white',
    poem: '陶舍重重依岸开，舟船日日顺江来',
    source: '《景德镇》· 无名氏',
    note: '景德镇白瓷，白如玉，薄如纸，声如磬',
  },
  {
    name: '玉色青',
    hex: '#5A9A80',
    rgb: '90,154,128',
    category: 'imagery',
    poem: '兰陵美酒郁金香，玉碗盛来琥珀光',
    source: '《客中行》· 李白',
    note: '和田青玉，温润内敛，君子比德',
  },
  {
    name: '琥珀色',
    hex: '#D4A040',
    rgb: '212,160,64',
    category: 'imagery',
    poem: '兰陵美酒郁金香，玉碗盛来琥珀光',
    source: '《客中行》· 李白',
    note: '琥珀色，酒液在玉碗中映光',
  },
  {
    name: '竹纸黄',
    hex: '#E8D890',
    rgb: '232,216,144',
    category: 'yellow',
    poem: '纸田墨稼，其乐洋洋',
    source: '《笔势》· 无名氏',
    note: '竹纸黄糙，古籍修复用，岁月沉淀',
  },
  {
    name: '绐帛青',
    hex: '#3A6A8A',
    rgb: '58,106,138',
    category: 'imagery',
    poem: '素以为绚，诗言志，歌永言',
    source: '《尚书》',
    note: '古时绢帛染青，文人书写',
  },
  {
    name: '青铜绿',
    hex: '#4A7A5A',
    rgb: '74,122,90',
    category: 'imagery',
    poem: '青铜器上铭文古，斑驳绿衣岁月深',
    source: '《青铜器》· 无名氏',
    note: '青铜器氧化后锈绿，称"青铜锈"',
  },
  {
    name: '朱砂红',
    hex: '#C02040',
    rgb: '192,32,64',
    category: 'red',
    poem: '印泥朱色盖文书，一诺千金信不虚',
    source: '《印章》· 无名氏',
    note: '印泥朱红，以朱砂调制，千年不褪',
  },
  {
    name: '鸡血石',
    hex: '#C03040',
    rgb: '192,48,64',
    category: 'red',
    poem: '石有灵犀通造化，天然鸡血艳如霞',
    source: '《昌化石》· 无名氏',
    note: '昌化鸡血石，印章名料，鲜红如血',
  },
  {
    name: '田黄石',
    hex: '#E8C060',
    rgb: '232,192,96',
    category: 'yellow',
    poem: '田黄温润胜黄金，御笔亲题价万金',
    source: '《田黄》· 无名氏',
    note: '寿山田黄石，印章皇后，萝卜纹如密',
  },
  {
    name: '青田石',
    hex: '#3A7A60',
    rgb: '58,122,96',
    category: 'imagery',
    poem: '青田石开印章红，镌刻方知翰墨工',
    source: '《青田石》· 无名氏',
    note: '浙江青田石，篆刻名料，色彩丰富',
  },
  {
    name: '端石紫',
    hex: '#5A3A6A',
    rgb: '90,58,106',
    category: 'imagery',
    poem: '端州石砚重人间，紫玉凝脂润笔端',
    source: '《端砚》· 无名氏',
    note: '端砚紫色，鱼脑冻白，青花点点',
  },
]
   
